"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-ERC8004-Receipts',
 'project_name': 'ReceiptsMesh Reputation Market',
 'track': 'Agents With Receipts',
 'pitch': 'A receipts-native identity and reputation rail for swarms that hire each '
          'other, settle work, and publish onchain usage evidence.',
 'idea_titles': ['Reputation-Gated Agent Marketplace',
                 'Credit-Scored Trading Agent',
                 'ENS-Only Reputation Exchange'],
 'architecture_summary': 'A receipt registry models identity anchors, operator '
                         'wallets, reputation updates, and task receipts with '
                         'machine-readable metadata. Python tooling assembles receipt '
                         'payloads, verifies schemas, and keeps agent.json and '
                         'agent_log.json aligned with future live registrations.',
 'overlap_targets': ['Olas',
                     'PayWithLocus',
                     'ENS',
                     'Bond.credit',
                     'OpenServ',
                     'Bankr Gateway'],
 'primary_contract_name': 'ReceiptsMeshRegistry',
 'primary_python_module': 'receipts_mesh',
 'category': 'identity',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'identity_state',
                       'description': 'Names, wallets, manifests, and verification '
                                      'proofs.'},
                      {'name': 'permissions',
                       'description': 'Which principals can act on which rails.'},
                      {'name': 'reputation_events',
                       'description': 'Receipts, scores, and attestation updates.'},
                      {'name': 'receipts',
                       'description': 'Submission notes and public evidence links.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for ReceiptsMeshRegistry.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'receipts_mesh.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Olas',
               'docs_url': 'https://docs.olas.network/',
               'env_vars': ['OLAS_API_KEY', 'OLAS_REQUEST_URL'],
               'endpoint_env': 'OLAS_REQUEST_URL',
               'action_kind': 'rest_json',
               'purpose': 'Hire and serve marketplace requests with receipts.'},
              {'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Bond.credit',
               'docs_url': 'https://bond.credit/',
               'env_vars': ['GMX_ORDER_URL', 'BOND_CREDIT_PROFILE_URL'],
               'endpoint_env': 'GMX_ORDER_URL',
               'action_kind': 'rest_json',
               'purpose': 'Journal bounded trades and credit-profile updates.'},
              {'name': 'OpenServ',
               'docs_url': 'https://docs.openserv.ai/',
               'env_vars': ['OPENSERV_API_KEY', 'OPENSERV_AGENT_URL'],
               'endpoint_env': 'OPENSERV_AGENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Dispatch jobs and expose swarm service endpoints.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'}],
 'actions': [{'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'olas_market_hire',
              'target': 'olas',
              'purpose': 'Use Olas for a bounded action in this repo.',
              'partner': 'Olas',
              'action_kind': 'rest_json',
              'max_amount_usd': 20,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Olas only after a dry-run artifact exists.',
                        'Use https://docs.olas.network/ for credential setup.']},
             {'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 85,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'bond_credit_credit_trade',
              'target': 'bond_credit',
              'purpose': 'Use Bond.credit for a bounded action in this repo.',
              'partner': 'Bond.credit',
              'action_kind': 'rest_json',
              'max_amount_usd': 90,
              'priority': 80,
              'sensitivity': 'high',
              'notes': ['Call Bond.credit only after a dry-run artifact exists.',
                        'Use https://bond.credit/ for credential setup.']},
             {'id': 'openserv_job_dispatch',
              'target': 'openserv',
              'purpose': 'Use OpenServ for a bounded action in this repo.',
              'partner': 'OpenServ',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call OpenServ only after a dry-run artifact exists.',
                        'Use https://docs.openserv.ai/ for credential setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 70,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
